version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: gestaopedidos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./backend-gestao-de-pedidos
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=gestaopedidos;Username=postgres;Password=senha
    ports:
      - "5158:5158"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend-gestao-de-pedidos
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://api:5158
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  pgdata: